name: build_test_umi_hos
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "待操作的底包/xiaomi.eu底包下载地址"
        required: true
        default: 'https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/V14.0.4.0.TJBCNXM/miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip?t=1706728803&s=7ffe68e09ea6bb89f743319b632a6ac7'
      PORT_URL:
        description: "待操作的移植包下载地址"
        required: true
    
      name:
        description: '版本号'
        default: 'test-UMI-OS1.0'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 最大化构建环境
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: 1.准备环境
        run: |
          sudo apt install aria2 python3 busybox zip tar apktool unzip p7zip-full openjdk-8-jre zipalign zstd bc xmlstarlet android-sdk-libsparse-utils
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome requests setuptools docopt
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
      - name: 2.克隆仓库
        run: |
          git clone --depth 1 https://github.com/Fer1d/HyperOS_Action hyperos_port
          cd hyperos_port
          sudo ./setup.sh
      - name: 3. 开始移植
        run: |
          cd hyperos_port
          sudo bash port.sh "${{ github.event.inputs.STOCK_URL }}" "${{ github.event.inputs.PORT_URL }}" | tee HyperOS_portlog.log
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "移植底包链接：${{ github.event.inputs.STOCK_URL }}" >> info.md
          echo "移植机型链接：${{ github.event.inputs.PORT_URL }}" >> info.md
          echo "tosasitill made with love 0202 & 0227" >> info.md
      - name: 4.上传ROM
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.name }}
          path: "/home/runner/work/HyperOS_Action/HyperOS_Action/hyperos_port/out/Workse"
          compression-level: 9
      - name: 5.上传Super.zst
        uses: actions/upload-artifact@v4
        with:
          name: super
          path: "/home/runner/work/HyperOS_Action/HyperOS_Action/hyperos_port/out/Workse/super.zst"
      - name: 6.发布
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "/home/runner/work/HyperOS_Action/HyperOS_Action/hyperos_port/HyperOS_portlog.log"
          bodyFile: "/home/runner/work/HyperOS_Action/HyperOS_Action/hyperos_port/info.md"
          tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 7.上传移植LOG
        uses: actions/upload-artifact@v4
        with:
          name: HyperOS-PortLOG
          path: "/home/runner/work/HyperOS_Action/HyperOS_Action/hyperos_port/HyperOS_portlog.log"
          compression-level: 9
